# Generated by Django 4.0 on 2022-01-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorand', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
